Algoritmo "Aula 37 - Contar 0 a 500"
// Soma dos numeros pares de 500 até 1000
Var

cont, resultado: inteiro


Inicio



   para cont de 500 ate 1000 faca               //contei de 0 até 6
         se cont mod 2 = 0 entao           // dos que contei, quem divido por 2 tem resto igual a zero
            resultado <- cont + resultado
         fimse
   fimpara
   
   escreval (resultado)


Fimalgoritmo