Algoritmo "Aula 05 - Fundação SE SENAO ENTAO"

Var
// TIPOS DE VARIAVEIS
inteiro - números redondos
real - números quebrados
caractere - sequencia de caracteres
logico - true ou false

idade: inteiro

// BLOCO FECHADO

Inicio

idade <-10 //idade recebe o valor de 10

  Se algumacoisa > 0 entao
  Senao algumacoisa = 4 entao
  Se algumacoisa = "caractere" entao
  Se algumacoisa > variavel entao
  Fimse
  
  

     
Fimalgoritmo