Algoritmo "Aula 02 - Aplicando Variaveis"

Var
// inteiro- nm inteiros
// real - nm com casas decimais
// caractere - cadeia caracteres
// logico - true or false (valores booleanos)
//nome escolhido: TIPO da variavel

idade: inteiro
nome: caractere
peso: real

Inicio
 escreval ("Escreva qual a sua idade?")
 leia (idade)

 escreval ("Qual seu nome?")
 leia (nome)
 
 escreval ("Qual seu peso?")
 leia (peso)

 
 escreva ("Obrigado por sua participação")


Fimalgoritmo